import Images from "../../Global/Images";

export const MyProjectsData = [
  {
    id: "1",
    fullName: "Linh Nguyen",
    firstName: "Linh",
    lastName: "Nguyen",
    userImage: [Images.User1, ""],
    status: "active",
    updateAt: "37 mins",
    isMessage: false,
  },
  {
    id: "2",
    fullName: "Seth Daniels",
    firstName: "Seth",
    lastName: "Daniels",
    userImage: ["SD", "#00875A"],
    status: "active",
    updateAt: "56 mins",
    isMessage: false,
  },
  {
    id: "3",
    fullName: "Genevieve Gonzalez",
    firstName: "Genevieve",
    lastName: "Gonzalez",
    userImage: [Images.User6, ""],
    status: "",
    updateAt: "10 mins",
    isMessage: false,
  },
  {
    id: "4",
    fullName: "Seth Daniels",
    firstName: "Seth",
    lastName: "Daniels",
    userImage: [Images.User7, ""],
    status: "active",
    updateAt: "5 mins",
    isMessage: true,
  },
  {
    id: "5",
    fullName: "Lucy Chavez",
    firstName: "Lucy",
    lastName: "Chavez",
    userImage: [Images.User8, ""],
    status: "active",
    updateAt: "40 mins",
    isMessage: false,
  },
];
